// src/config/driveIds.ts
import { env, envRK } from "@/lib/env";

/** Central place to read all Drive IDs without changing your .env.
 *  Primary keys match your current naming; fallbacks cover alt names used in some code paths.
 */
export const IDS = {
  // Auth / users
  USERS_FILE_ID: env("VITE_DRIVE_USERS_FILE_ID"),

  // Athleten
  ATHLETEN_FILE_ID: env("VITE_DRIVE_ATHLETEN_FILE_ID"),

  // Übungskatalog / -pflege
  UEBUNGEN_FILE_ID: env("VITE_DRIVE_UEBUNGEN_FILE_ID", "VITE_DRIVE_UEBUNGSKATALOG_FILE_ID"),
  UEBUNGSGRUPPEN_FILE_ID: env("VITE_DRIVE_UEBUNGSGRUPPEN_FILE_ID"),
  UEBUNGSPFLEGE_FILE_ID: env("VITE_DRIVE_UEBUNGSPFLEGE_FILE_ID"),

  // Anmeldung (LG)
  ANMELDUNG_FILE_ID: env("VITE_DRIVE_LG_ANMELDUNG_FILE_ID", "VITE_DRIVE_ANMELDUNG_FILE_ID"),

  // Kindertraining
  KT_PERSONEN_FILE_ID: env("VITE_DRIVE_KINDERTRAINING_PERSONEN_FILE_ID"),
  KT_DATA_FILE_ID: env("VITE_DRIVE_KINDERTRAINING_FILE_ID", "VITE_DRIVE_KINDERTRAINING_DATA_FILE_ID"),

  // Trainingsplan
  TRAININGSPLAN_FOLDER_ID: env("VITE_DRIVE_TRAININGSPLAENE_FOLDER_ID", "VITE_DRIVE_TRAININGSPLAN_FOLDER_ID"),
  TRAININGSPLAN_FILE_ID: env("VITE_DRIVE_TRAININGSPLAN_FILE_ID"),
  TRAININGSBLOECKE_FILE_ID: env("VITE_DRIVE_TRAININGSBLOECKE_FILE_ID"),
  TRAININGSBLOECKE_GROUPS_FILE_ID: env("VITE_DRIVE_TRAININGSBLOECKE_GROUPS_FILE_ID"),

  // Media
  MEDIA_FOLDER_ID: env("VITE_DRIVE_MEDIA_FOLDER_ID"),
} as const;

export type DriveIds = typeof IDS;

/** Optional resource keys (only needed if your share links include ?resourcekey=...). */
export const RK = {
  USERS: envRK("VITE_DRIVE_USERS_FILE_RESOURCE_KEY"),
  ATHLETEN: envRK("VITE_DRIVE_ATHLETEN_FILE_RESOURCE_KEY"),
  UEBUNGEN: envRK("VITE_DRIVE_UEBUNGEN_FILE_RESOURCE_KEY", "VITE_DRIVE_UEBUNGSKATALOG_FILE_RESOURCE_KEY"),
  UEBUNGSPFLEGE: envRK("VITE_DRIVE_UEBUNGSPFLEGE_FILE_RESOURCE_KEY"),
  ANMELDUNG: envRK("VITE_DRIVE_LG_ANMELDUNG_FILE_RESOURCE_KEY", "VITE_DRIVE_ANMELDUNG_FILE_RESOURCE_KEY"),
  KT_PERSONEN: envRK("VITE_DRIVE_KINDERTRAINING_PERSONEN_FILE_RESOURCE_KEY"),
  KT_DATA: envRK("VITE_DRIVE_KINDERTRAINING_FILE_RESOURCE_KEY", "VITE_DRIVE_KINDERTRAINING_DATA_FILE_RESOURCE_KEY"),
  TRAININGSPLAN_FILE: envRK("VITE_DRIVE_TRAININGSPLAN_FILE_RESOURCE_KEY"),
} as const;
